# Generated by Django 4.2.1 on 2023-07-02 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boardcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movie'),
        ),
    ]
